ds:
  checkpoint: Madjakul/HALvest-Contrastive-Raw
  streaming: False

sampler:
  do_sample: True
  batch_size: 10
  soft_positive: False
  n_pairs: 100
  n_sentences: 2
  load_from_cache_file: True
  do_push_to_hub: False

ict_sampler:
  do_sample: True
  batch_size: 10
  n_pairs: 10
  n_sentences: 2
  load_from_cache_file: True
  do_push_to_hub: False
