main:
  do_compress: False
  do_checksum: False
  do_push_to_hub: False

ds:
  checkpoint: Madjakul/HALvest-Contrastive-Raw
  streaming: False
  # cache_dir: /cache

sampler:
  num_pairs: 100
  alpha: 0.5
  num_sentences: 2
