ds:
  checkpoint: Madjakul/HALvest-Contrastive-Raw
  push_checkpoint: Madjakul/HALvest-Contrastive-R
  streaming: False

sampler:
  do_sample: True
  batch_size: 1000
  soft_positives: True
  n_pairs: 2
  n_sentences: 2
  load_from_cache_file: True
  do_push_to_hub: True

ict_sampler:
  do_sample: True
  batch_size: 1000
  n_pairs: 6
  n_sentences: 2
  load_from_cache_file: True
  do_push_to_hub: True
